services:
  nodeapp:
    build: .
    container_name: blog-node-app
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: 
      - .env.docker
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: blog-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DEV_USERNAME}
      POSTGRES_PASSWORD: ${DEV_PASSWORD}
      POSTGRES_DB: ${DEV_DATABASE}
    ports:
      - "${DEV_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: blog-redis
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  pgdata:
